# Generated by Django 5.1.5 on 2025-06-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
