# Generated by Django 5.1.5 on 2025-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('confidence_threshold', models.IntegerField(default=70)),
                ('auto_execute', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=1)),
                ('performance_rate', models.FloatField(blank=True, null=True)),
                ('validity_minutes', models.IntegerField(default=60)),
                ('required_bars', models.PositiveIntegerField(default=50)),
                ('execution_mode', models.CharField(choices=[('simulated', 'Simulated'), ('paper', 'Paper'), ('live', 'Live')], default='simulated', max_length=10)),
                ('priority', models.CharField(choices=[('confirm', 'Confirm'), ('primary', 'Primary'), ('context', 'Context')], default='primary', max_length=10)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1mo', '1 Month')], default='1m', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
