# Generated by Django 5.1.5 on 2025-06-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedtrade',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_trades', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='technicalindicator',
            name='market_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='backtesting.historicalmarketdatapoint'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['timestamp', 'timeframe'], name='backtesting_timesta_f2d640_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedtrade',
            index=models.Index(fields=['strategy_name', 'timeframe'], name='backtesting_strateg_9b6305_idx'),
        ),
        migrations.AddIndex(
            model_name='simulatedtrade',
            index=models.Index(fields=['entry_time', 'exit_time'], name='backtesting_entry_t_a243b6_idx'),
        ),
    ]
