# Generated by Django 5.1.5 on 2025-06-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usd_balance', models.FloatField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('avg_price', models.FloatField(default=0)),
                ('last_buy', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trades.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.IntegerField(default=0)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('notional', models.FloatField(blank=True, null=True)),
                ('filled_notional', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('trailing_stop', models.FloatField(blank=True, null=True)),
                ('trailing_level', models.FloatField(blank=True, null=True)),
                ('highest_price', models.FloatField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit')], default='market', max_length=20)),
                ('time_in_force', models.CharField(choices=[('day', 'Day'), ('gtc', 'GTC'), ('opg', 'Open'), ('cls', 'Close'), ('ioc', 'IOC'), ('fok', 'FOK')], default='day', max_length=10)),
                ('execution_mode', models.CharField(choices=[('simulated', 'Simulated'), ('paper', 'Paper'), ('live', 'Live')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='executed', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.IntegerField()),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('slippage', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(default=0)),
                ('min_price_seen', models.FloatField(blank=True, null=True)),
                ('max_price_seen', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
                ('triggered_by', models.ManyToManyField(to='signals.signal')),
            ],
            options={
                'db_table': 'core_trade',
            },
        ),
    ]
