# Generated by Django 5.1.5 on 2025-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('risk_pct', models.FloatField(default=0.05)),
                ('min_notional', models.FloatField(default=10)),
                ('conflict_threshold', models.FloatField(default=10)),
                ('primary_min_score', models.IntegerField(default=60)),
                ('primary_group_avg_score', models.IntegerField(default=50)),
                ('confirm_min_avg_score', models.IntegerField(default=50)),
                ('context_confirm_avg_score', models.IntegerField(default=50)),
                ('sl_buffer_pct', models.FloatField(default=0.03)),
                ('tp_buffer_pct', models.FloatField(default=0.06)),
                ('trailing_stop_pct', models.FloatField(default=0.02)),
                ('weight_primary', models.FloatField(default=1.0)),
                ('weight_context', models.FloatField(default=0.7)),
                ('weight_confirm', models.FloatField(default=0.5)),
            ],
        ),
    ]
