# Generated by Django 5.1.5 on 2025-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('watch', 'Watch')], max_length=20)),
                ('price', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='alpaca_websocket', max_length=50)),
                ('executed', models.BooleanField(default=False)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day')], default='1m', max_length=5)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
