# Generated by Django 5.1.5 on 2025-06-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('signals', '0001_initial'),
        ('strategies', '0001_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='related_trades',
            field=models.ManyToManyField(blank=True, to='trades.trade'),
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.openstrategy'),
        ),
        migrations.AddField(
            model_name='signal',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol'),
        ),
    ]
