# Generated by Django 5.1.5 on 2025-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtestingV2', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrade',
            name='triggered_by',
            field=models.ManyToManyField(to='signals.signal'),
        ),
        migrations.AddField(
            model_name='historicalsignal',
            name='related_trades',
            field=models.ManyToManyField(blank=True, to='backtestingV2.historicaltrade'),
        ),
        migrations.AddIndex(
            model_name='historicalmarketdatapoint',
            index=models.Index(fields=['symbol', 'timeframe', 'start_time'], name='backtesting_symbol__36ebfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalmarketdatapoint',
            unique_together={('symbol', 'timeframe', 'start_time')},
        ),
    ]
