# Generated by Django 5.1.5 on 2025-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetechnicalindicator',
            name='sma_12',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livetechnicalindicator',
            name='sma_26',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livetechnicalindicator',
            name='sma_30',
            field=models.FloatField(null=True),
        ),
    ]
